name: Release

on:
  workflow_call:
    inputs:
      repo_owner:
        required: true
        type: string
      repo_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Tests
        uses: ${{ inputs.repo_owner }}/github-actions/.github/actions/run-make-test@main

      - name: Tap Homebrew
        uses: ${{ inputs.repo_owner }}/github-actions/.github/actions/tap-homebrew-repo@main
        with:
          repo_owner: ${{ inputs.repo_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump Version
        id: bump
        uses: ${{ inputs.repo_owner }}/github-actions/.github/actions/bump-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: ${{ inputs.repo_owner }}/github-actions/.github/actions/create-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.bump.outputs.new_version }}

      - name: Update Formula In-Place
        uses: ${{ inputs.repo_owner }}/github-actions/.github/actions/update-formula@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.bump.outputs.new_version }}
          repo: ${{ github.repository }}
          action_name: ${{ github.workflow }}

      - name: Mirror Formula to homebrew-tap
        uses: ${{ inputs.repo_owner }}/github-actions/.github/actions/publish-to-tap@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          version: ${{ steps.bump.outputs.new_version }}
          repo_owner: ${{ inputs.repo_owner }}
          repo_name: ${{ inputs.repo_name }}
