name: Release

on:
  workflow_call:
    inputs:
      repo_owner:
        required: true
        type: string
      repo_name:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Tests
        uses: adelynnmckay/github-actions/.github/actions/run-make-test@main

      - name: Tap Homebrew
        uses: adelynnmckay/github-actions/.github/actions/tap-homebrew-repo@main
        with:
          repo_owner: ${{ inputs.repo_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump Version
        id: bump
        uses: adelynnmckay/github-actions/.github/actions/bump-version@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Release (update formula, tag, release)
        uses: adelynnmckay/github-actions/.github/actions/prepare-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.bump.outputs.new_version }}
          repo: ${{ github.repository }}
          action_name: ${{ github.workflow }}

